import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Header from "./components/Header";
import Footer from "./components/Footer";
import ReducerProvider from "./components/ReducerProvider";
import HeaderWrapper from "./components/HeaderWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {  
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReducerProvider>
          <HeaderWrapper />
          {children}
          <Footer />
        </ReducerProvider>

      </body>
    </html>
  );
}





// export default function RootLayout({
//   children,
//   params : {[keys:string]}
// }: Readonly<{
//   children: React.ReactNode;
// }>) {